### ISSUE TITLE
Pas de correspondances id renvoyés

### ISSUE THREAD

**Issue by CelineLesne** [BaseAdresseNationale/addok-docker#25]
Bonjour, 

J'ai constaté après avoir géocodé un gros volume de données que bon nombre d'ID BAN (11 millions sur 17 millions géocodés) renvoyé par l'API ne trouvent pas correspondance avec ceux présents dans le référentiel BAN. 
En regardant de + près j'ai remarqué que les id concernés étaient ceux d'adresses géocodés à la précision street. Les ID renvoyés sont plus court (seulement le code postale et l'id fantoire). 

Pour l'exemple l'adresse suivante "Rue de Cade 34160 Castrie" est géocodée par l'API avec l'ID BAN suivant : 34058_0146, qui n'existe pas dans les données fournies par ETALAB. Cependant l'adresse en question est bien présente dans les données mais sous un autre ID BAN : 34058_0146_e8f29d.

Ayant besoin de faire du lien par cet ID entre le référentiel adresse et mes entité géocodés serait-il possible de trouver une solution pour que l'api renvoie les même ID que ceux du référentiel lors des cas de géocodage à l'échelle de le rue ? 

Je vous remercie par avance pour vos réponses 👍 

Céline Lesné

**Comment by jdesboeufs** [comment]
Les fichiers CSV que vous téléchargez contiennent exclusivement les adresses.
Les identifiants de voies ne sont pas présents dans ces fichiers. C'est une piste d'évolution que de fournir un fichier complémentaire avec les voies. Je l'ajoute dans notre liste, nous travaillons sur la feuille de route 2022.
En attendant vous pouvez interroger une API "privée" : https://plateforme.adresse.data.gouv.fr/lookup/34058_0146
(performances non garanties à ce stade)
