### ISSUE TITLE
Fichiers volumineux pour géocodage de masse

### ISSUE THREAD

**Issue by fabien-cat** [BaseAdresseNationale/addok-docker#27]
Bonjour,

Avec le géocodage de masse _/search/csv/_ on obtient une erreur avec un fichier csv supérieur à un peu plus de 1000 lignes (mais fichier inférieur à 50Mo) : 
**`internal server error`**

Est ce qu'il y a une configuration à adapter pour traiter les fichiers volumineux ? redis ou docker ?

Merci

**Comment by ThomasG77** [comment]
Bonjour,

Vous avez essayé de changer `WORKER_TIMEOUT`
Il est à 30 sec par défaut.

Sinon pour consommer, découper vos gros fichiers. Pour cela, vous pouvez regarder du coté de https://github.com/MTES-MCT/bulk-geocoding-python-client
 ou bien du code https://addok.readthedocs.io/en/latest/examples/

**Comment by jdesboeufs** [comment]
Ou bien https://github.com/jdesboeufs/addok-geocode-stream

**Comment by fabien-cat** [comment]
Bonjour,

On a augmenté le nombre de worker et on est passé à une capacité 100K lignes. 
On a adapté la config de redis aux ressources du serveur mais ça n'a rien changé.
Pour satisfaire nos besoins, on fait du traitement par lot avec le code de MTES-MCT.
On testera peut-être plus tard le géocodage avec Node.JS.

Merci pour vos réponses qui nous ont bien aidé 👍
